

--STEP: 1
CREATE Index WRK_ACCT0723_IDX ON MDM_WRK.ACCT_20200723 (TRIM(ACCT_NUM),SRC_SYS_CD,ACCT_CLS_DT);

--STEP: 2
UPDATE /*+ enable_parallel_dml parallel(16) append */ MDM_WRK.ACCT A 
  SET A.ACCT_CLS_DT = (SELECT /*+ parallel(16) */  BKP.ACCT_CLS_DT
                       FROM MDM_WRK.ACCT_20200723 BKP
                       WHERE TRIM(BKP.ACCT_NUM) = TRIM(A.ACCT_NUM) AND A.SRC_SYS_CD = 'IM' AND A.SRC_SYS_CD = BKP.SRC_SYS_CD
                             AND A.ACCT_CLS_DT IS NULL AND A.EXTR_DT_NUM = '20200724'),
  A.EXTR_DT_NUM = (SELECT /*+ parallel(16) */  '20200813'
                       FROM MDM_WRK.ACCT_20200723 BKP
                       WHERE TRIM(BKP.ACCT_NUM) = TRIM(A.ACCT_NUM) AND A.SRC_SYS_CD = 'IM' AND A.SRC_SYS_CD = BKP.SRC_SYS_CD
                             AND A.ACCT_CLS_DT IS NULL AND A.EXTR_DT_NUM = '20200724'
                             AND A.ACCT_OPN_DT NOT IN (TO_DATE('23-JUL-20','DD-MON-YY'),  TO_DATE('24-JUL-20','DD-MON-YY')))  
WHERE A.SRC_SYS_CD = 'IM' 
AND TRIM(A.ACCT_CLS_DT) IS NULL 
AND A.EXTR_DT_NUM = '20200724'
AND A.ACCT_OPN_DT NOT IN  (TO_DATE('23-JUL-20','DD-MON-YY'),  TO_DATE('24-JUL-20','DD-MON-YY'));

--STEP: 3
COMMIT;



